#!/usr/bin/env bash

JAR_FILE="target/airline-examples.jar"

EXAMPLE=$1
shift
if [ -z "${EXAMPLE}" ]; then
  echo "No example specified to run"
  echo "Usage is ./runExample ExampleClass [Command [Options]]"
  exit 1
fi

# Strip .class/.java if specified
EXAMPLE="${EXAMPLE%.class}"
EXAMPLE="${EXAMPLE%.java}"

# Locate the example class name
CLASS=$(find src/main/java/com/github/rvesse/airline/examples -name ${EXAMPLE}.java)
if [ -z "${CLASS}" ]; then
  echo "${EXAMPLE} does not appear to be an example that can be run"
  exit 1
fi

# Convert filename to Java class name
# Remove leading src/main/java
# Replace / with .
# Remove trailing .java
CLASS="${CLASS#src/main/java/}"
CLASS="${CLASS//\//.}"
CLASS="${CLASS%.java}"

if [ ! -f "${JAR_FILE}" ]; then
  echo "Examples JAR ${JAR_FILE} does not yet exist, please run mvn package to build"
  exit 1
fi

java -cp "${JAR_FILE}" ${CLASS} "$@"